Add user-systemd package
Includes user-py-elftools packgage that it depends on. Specific
build flags are based on what is used for Talos Linux
(https://github.com/siderolabs/pkgs/blob/main/systemd/pkg.yaml) but
currently with selinux disabled because of missing libselinux
dependency:
```
ERROR: Dependency "libselinux" not found (tried pkg-config and cmake)
```